language: rust
rust:
  - 1.61.0 # MSRV
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
script: cargo build --verbose && cargo test --verbose &&
  cargo build --verbose --all-features && cargo test --verbose --all-features
